# Generated by Django 3.2.4 on 2021-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsextraction', '0003_auto_20210706_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='vehicleCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='vehicleNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
