# Generated by Django 3.2.4 on 2021-07-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rssdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('death', models.CharField(blank=True, max_length=200, null=True)),
                ('death_no', models.IntegerField(blank=True, default=0, null=True)),
                ('injury', models.CharField(blank=True, max_length=200, null=True)),
                ('injury_no', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, default=datetime.date.today, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rssdata',
                'ordering': ('-date', 'location'),
            },
        ),
    ]
