# Generated by Django 3.2.4 on 2021-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsextraction', '0002_alter_rssdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdata',
            name='body',
            field=models.TextField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='header',
            field=models.CharField(blank=True, max_length=200, unique_for_date=True),
        ),
    ]
